name: Build

on: [push, pull_request]

jobs:
  container-build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64_devkitarm
    steps:
      - name: build - test
        run: |
          echo "test1" > test.txt
      - name: store - test
        uses: actions/upload-artifact@v2
        with:
          name: test.txt
          path: test.txt
      - name: build - test2
        run: |
          echo "test2" > test2.txt
      - name: store - test2
        uses: actions/upload-artifact@v2
        with:
          name: test2.txt
          path: test2.txt
  nightly:
    needs: [container-build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/ci'
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./artifacts_raw
      - name: Flatten artifacts tree
        run: |
          mkdir artifacts
          find ./artifacts_raw -type f -exec mv {} ./artifacts \;
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest successful build"
          files: |
            artifacts/*